In [1]:
import numpy as np
import pandas as pd

In [2]:
train_dataset = pd.read_csv("/kaggle/input/competitions/playground-series-s6e3/train.csv")
test_dataset = pd.read_csv("/kaggle/input/competitions/playground-series-s6e3/test.csv")

In [3]:
train_dataset

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,...,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,...,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,594189,Male,0,No,No,57,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),97.55,5460.70,No
594190,594190,Female,0,No,No,72,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),91.95,6782.15,No
594191,594191,Female,0,Yes,No,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.40,1871.90,No
594192,594192,Female,0,No,No,32,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,86.00,2847.20,No
594193,594193,Female,1,Yes,No,2,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,Yes,Electronic check,54.55,108.05,Yes

In [4]:
test_dataset

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,594194,Female,0,Yes,No,72,Yes,Yes,Fiber optic,Yes,Yes,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,115.55,8061.50
1,594195,Female,0,Yes,No,71,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Bank transfer (automatic),19.80,1336.50
2,594196,Male,0,No,No,12,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),55.55,633.55
3,594197,Male,0,Yes,Yes,71,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,Two year,No,Credit card (automatic),84.10,6457.15
4,594198,Female,0,No,No,15,Yes,No,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,No,Electronic check,90.35,1233.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254650,848844,Male,0,Yes,Yes,72,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),19.95,1443.65
254651,848845,Male,1,Yes,No,16,Yes,Yes,Fiber optic,No,No,No,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,100.15,1563.50
254652,848846,Male,0,Yes,No,35,Yes,Yes,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),105.80,3132.75
254653,848847,Female,0,No,No,25,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),20.25,511.25
254654,848848,Female,0,No,No,24,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),90.10,2172.05

In [5]:
train_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 594194 entries, 0 to 594193
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                594194 non-null  int64
 1   gender            594194 non-null  object
 2   SeniorCitizen     594194 non-null  int64
 3   Partner           594194 non-null  object
 4   Dependents        594194 non-null  object
 5   tenure            594194 non-null  int64
 6   PhoneService      594194 non-null  object
 7   MultipleLines     594194 non-null  object
 8   InternetService   594194 non-null  object
 9   OnlineSecurity    594194 non-null  object
 10  OnlineBackup      594194 non-null  object
 11  DeviceProtection  594194 non-null  object
 12  TechSupport       594194 non-null  object
 13  StreamingTV       594194 non-null  object
 14  StreamingMovies   594194 non-null  object
 15  Contract          594194 non-null  object
 16  PaperlessBilling  594194 non-null  object
 17  PaymentMethod     594194 non-null  object
 18  MonthlyCharges    594194 non-null  float64
 19  TotalCharges      594194 non-null  float64
 20  Churn             594194 non-null  object
dtypes: float64(2), int64(3), object(16)
memory usage: 95.2+ MB

In [6]:
test_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254655 entries, 0 to 254654
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                254655 non-null  int64
 1   gender            254655 non-null  object
 2   SeniorCitizen     254655 non-null  int64
 3   Partner           254655 non-null  object
 4   Dependents        254655 non-null  object
 5   tenure            254655 non-null  int64
 6   PhoneService      254655 non-null  object
 7   MultipleLines     254655 non-null  object
 8   InternetService   254655 non-null  object
 9   OnlineSecurity    254655 non-null  object
 10  OnlineBackup      254655 non-null  object
 11  DeviceProtection  254655 non-null  object
 12  TechSupport       254655 non-null  object
 13  StreamingTV       254655 non-null  object
 14  StreamingMovies   254655 non-null  object
 15  Contract          254655 non-null  object
 16  PaperlessBilling  254655 non-null  object
 17  PaymentMethod     254655 non-null  object
 18  MonthlyCharges    254655 non-null  float64
 19  TotalCharges      254655 non-null  float64
dtypes: float64(2), int64(3), object(15)
memory usage: 38.9+ MB

In [7]:
train = train_dataset.copy()
test = test_dataset.copy()

In [8]:
train = train.drop(columns = ["id"])
test = test.drop(columns = ["id"])

In [9]:
train['gender'].describe()

count     594194
unique         2
top       Female
freq      298738
Name: gender, dtype: object

In [10]:
train['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [11]:
train['gender'].value_counts()

gender
Female    298738
Male      295456
Name: count, dtype: int64

In [12]:
train = train.rename(columns = {'gender': 'Gender'})
test = test.rename(columns = {'gender': 'Gender'})

In [13]:
train['Gender'] = train['Gender'].map({'Male': 0, 'Female': 1})
test['Gender'] = test['Gender'].map({'Male': 0, 'Female': 1})

In [14]:
train['SeniorCitizen'].describe()

count    594194.000000
mean          0.114102
std           0.317936
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: SeniorCitizen, dtype: float64

In [15]:
train['SeniorCitizen'].unique()

array([0, 1])

In [16]:
train['SeniorCitizen'].value_counts()

SeniorCitizen
0    526395
1     67799
Name: count, dtype: int64

In [17]:
train['Partner'].describe()

count     594194
unique         2
top          Yes
freq      309554
Name: Partner, dtype: object

In [18]:
train['Partner'].unique()

array(['Yes', 'No'], dtype=object)

In [19]:
train['Partner'].value_counts()

Partner
Yes    309554
No     284640
Name: count, dtype: int64

In [20]:
train['Partner'] = train['Partner'].map({'Yes': 1, 'No': 0})
test['Partner'] = test['Partner'].map({'Yes': 1, 'No': 0})

In [21]:
train['Dependents'].describe()

count     594194
unique         2
top           No
freq      414362
Name: Dependents, dtype: object

In [22]:
train['Dependents'].unique()

array(['Yes', 'No'], dtype=object)

In [23]:
train['Dependents'].value_counts()

Dependents
No     414362
Yes    179832
Name: count, dtype: int64

In [24]:
train['Dependents'] = train['Dependents'].map({'Yes': 1, 'No': 0})
test['Dependents'] = test['Dependents'].map({'Yes': 1, 'No': 0})

In [25]:
train['tenure'].describe()

count    594194.000000
mean         36.577258
std          25.061922
min           1.000000
25%          12.000000
50%          35.000000
75%          62.000000
max          72.000000
Name: tenure, dtype: float64

In [26]:
train['tenure'].unique()

array([29, 58,  1, 24, 72, 55, 13, 67, 33, 63,  3, 31, 27, 52, 68, 35, 66,
       17, 59, 61, 12, 37, 64, 23,  9,  8, 15, 18, 19, 51,  5, 71, 60, 62,
       45, 69, 40, 53, 54, 34,  2, 70, 39, 41,  4, 22, 46, 28, 42, 48, 21,
       43, 14, 10, 47,  7, 57, 36, 16, 26, 20, 50, 30, 11, 44, 25, 56,  6,
       65, 38, 49, 32])

In [27]:
train['tenure'].value_counts()

tenure
72    56411
1     29182
71    20763
2     16766
3     13478
      ...
40     4203
21     3862
44     3496
39     3396
36     2562
Name: count, Length: 72, dtype: int64

In [28]:
train = train.rename(columns = {'tenure': 'Tenure'})
test = test.rename(columns = {'tenure': 'Tenure'})

In [29]:
bins = [0, 12, 24, 36, 48, 60, 72]
labels = [1, 2, 3, 4, 5, 6]

train['Tenure'] = pd.cut(train['Tenure'], bins = bins, labels = labels)
test['Tenure'] = pd.cut(test['Tenure'], bins = bins, labels = labels)

In [30]:
train['PhoneService'].describe()

count     594194
unique         2
top          Yes
freq      557893
Name: PhoneService, dtype: object

In [31]:
train['PhoneService'].unique()

array(['Yes', 'No'], dtype=object)

In [32]:
train['PhoneService'].value_counts()

PhoneService
Yes    557893
No      36301
Name: count, dtype: int64

In [33]:
train['PhoneService'] = train['PhoneService'].map({'Yes': 1, 'No': 0})
test['PhoneService'] = test['PhoneService'].map({'Yes': 1, 'No': 0})

In [34]:
train['MultipleLines'].describe()

count     594194
unique         3
top           No
freq      283384
Name: MultipleLines, dtype: object

In [35]:
train['MultipleLines'].unique()

array(['No', 'Yes', 'No phone service'], dtype=object)

In [36]:
train['MultipleLines'].value_counts()

MultipleLines
No                  283384
Yes                 274509
No phone service     36301
Name: count, dtype: int64

In [37]:
train['MultipleLines'] = train['MultipleLines'].map({'Yes': 1, 'No': 0, 'No phone service': 0})
test['MultipleLines'] = test['MultipleLines'].map({'Yes': 1, 'No': 0, 'No phone service': 0})

In [38]:
train['InternetService'].describe()

count          594194
unique              3
top       Fiber optic
freq           272386
Name: InternetService, dtype: object

In [39]:
train['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [40]:
train['InternetService'].value_counts()

InternetService
Fiber optic    272386
DSL            181081
No             140727
Name: count, dtype: int64

In [41]:
train["InternetService_DSL"] = (train["InternetService"] == "DSL").astype(int)
train["InternetService_FiberOptic"] = (train["InternetService"] == "Fiber optic").astype(int)

test["InternetService_DSL"] = (test["InternetService"] == "DSL").astype(int)
test["InternetService_FiberOptic"] = (test["InternetService"] == "Fiber optic").astype(int)

In [42]:
train.drop(columns=["InternetService"], inplace = True)
test.drop(columns=["InternetService"],  inplace = True)

In [43]:
train_cols = list(train.columns)
test_cols = list(test.columns)

train_cols.insert(7, train_cols.pop(19))
train_cols.insert(8, train_cols.pop(20))
train = train[train_cols]

test_cols.insert(7, test_cols.pop(18))
test_cols.insert(8, test_cols.pop(19))
test = test[test_cols]

In [44]:
train['OnlineSecurity'].describe()

count     594194
unique         3
top           No
freq      289474
Name: OnlineSecurity, dtype: object

In [45]:
train['OnlineSecurity'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [46]:
train['OnlineSecurity'].value_counts()

OnlineSecurity
No                     289474
Yes                    163993
No internet service    140727
Name: count, dtype: int64

In [47]:
train['OnlineSecurity'] = train['OnlineSecurity'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
test['OnlineSecurity'] = test['OnlineSecurity'].map({'Yes': 1, 'No': 0, 'No internet service': 0})

In [48]:
train['OnlineBackup'].describe()

count     594194
unique         3
top           No
freq      250083
Name: OnlineBackup, dtype: object

In [49]:
train['OnlineBackup'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [50]:
train['OnlineBackup'].value_counts()

OnlineBackup
No                     250083
Yes                    203384
No internet service    140727
Name: count, dtype: int64

In [51]:
train['OnlineBackup'] = train['OnlineBackup'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
test['OnlineBackup'] = test['OnlineBackup'].map({'Yes': 1, 'No': 0, 'No internet service': 0})

In [52]:
train['DeviceProtection'].describe()

count     594194
unique         3
top           No
freq      247377
Name: DeviceProtection, dtype: object

In [53]:
train['DeviceProtection'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [54]:
train['DeviceProtection'].value_counts()

DeviceProtection
No                     247377
Yes                    206090
No internet service    140727
Name: count, dtype: int64

In [55]:
train['DeviceProtection'] = train['DeviceProtection'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
test['DeviceProtection'] = test['DeviceProtection'].map({'Yes': 1, 'No': 0, 'No internet service': 0})

In [56]:
train['TechSupport'].describe()

count     594194
unique         3
top           No
freq      288571
Name: TechSupport, dtype: object

In [57]:
train['TechSupport'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [58]:
train['TechSupport'].value_counts()

TechSupport
No                     288571
Yes                    164896
No internet service    140727
Name: count, dtype: int64

In [59]:
train['TechSupport'] = train['TechSupport'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
test['TechSupport'] = test['TechSupport'].map({'Yes': 1, 'No': 0, 'No internet service': 0})

In [60]:
train['StreamingTV'].describe()

count     594194
unique         3
top          Yes
freq      240301
Name: StreamingTV, dtype: object

In [61]:
train['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [62]:
train['StreamingTV'].value_counts()

StreamingTV
Yes                    240301
No                     213166
No internet service    140727
Name: count, dtype: int64

In [63]:
train['StreamingTV'] = train['StreamingTV'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
test['StreamingTV'] = test['StreamingTV'].map({'Yes': 1, 'No': 0, 'No internet service': 0})

In [64]:
train['StreamingMovies'].describe()

count     594194
unique         3
top          Yes
freq      241435
Name: StreamingMovies, dtype: object

In [65]:
train['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [66]:
train['StreamingMovies'].value_counts()

StreamingMovies
Yes                    241435
No                     212032
No internet service    140727
Name: count, dtype: int64

In [67]:
train['StreamingMovies'] = train['StreamingMovies'].map({'Yes': 1, 'No': 0, 'No internet service': 0})
test['StreamingMovies'] = test['StreamingMovies'].map({'Yes': 1, 'No': 0, 'No internet service': 0})

In [68]:
train['Contract'].describe()

count             594194
unique                 3
top       Month-to-month
freq              298918
Name: Contract, dtype: object

In [69]:
train['Contract'].unique()

array(['One year', 'Two year', 'Month-to-month'], dtype=object)

In [70]:
train['Contract'].value_counts()

Contract
Month-to-month    298918
Two year          186943
One year          108333
Name: count, dtype: int64

In [71]:
train['Contract'] = train['Contract'].map({'Month-to-month': 0, 'One year': 1, 'Two year': 2})
test['Contract'] = test['Contract'].map({'Month-to-month': 0, 'One year': 1, 'Two year': 2})

In [72]:
train['PaperlessBilling'].describe()

count     594194
unique         2
top          Yes
freq      365579
Name: PaperlessBilling, dtype: object

In [73]:
train['PaperlessBilling'].unique()

array(['Yes', 'No'], dtype=object)

In [74]:
train['PaperlessBilling'].value_counts()

PaperlessBilling
Yes    365579
No     228615
Name: count, dtype: int64

In [75]:
train['PaperlessBilling'] = train['PaperlessBilling'].map({'Yes': 1, 'No': 0})
test['PaperlessBilling'] = test['PaperlessBilling'].map({'Yes': 1, 'No': 0})

In [76]:
train['PaymentMethod'].describe()

count               594194
unique                   4
top       Electronic check
freq                215372
Name: PaymentMethod, dtype: object

In [77]:
train['PaymentMethod'].unique()

array(['Mailed check', 'Credit card (automatic)', 'Electronic check',
       'Bank transfer (automatic)'], dtype=object)

In [78]:
train['PaymentMethod'].value_counts()

PaymentMethod
Electronic check             215372
Credit card (automatic)      133705
Mailed check                 123757
Bank transfer (automatic)    121360
Name: count, dtype: int64

In [79]:
train["PaymentMethod_ElectronicCheck"] = (train["PaymentMethod"] == "Electronic check").astype(int)
train["PaymentMethod_MailedCheck"] = (train["PaymentMethod"] == "Mailed check").astype(int)
train["PaymentMethod_CreditCard"] = (train["PaymentMethod"] == "Credit card (automatic)").astype(int)
train["PaymentMethod_BankTransfer"] = (train["PaymentMethod"] == "Bank transfer (automatic)").astype(int)

test["PaymentMethod_ElectronicCheck"] = (test["PaymentMethod"] == "Electronic check").astype(int)
test["PaymentMethod_MailedCheck"] = (test["PaymentMethod"] == "Mailed check").astype(int)
test["PaymentMethod_CreditCard"] = (test["PaymentMethod"] == "Credit card (automatic)").astype(int)
test["PaymentMethod_BankTransfer"] = (test["PaymentMethod"] == "Bank transfer (automatic)").astype(int)

In [80]:
train.drop(columns=["PaymentMethod"], inplace = True)
test.drop(columns=["PaymentMethod"],  inplace = True)

In [81]:
train_cols = list(train.columns)
test_cols = list(test.columns)

train_cols.insert(17, train_cols.pop(20))
train_cols.insert(18, train_cols.pop(21))
train_cols.insert(19, train_cols.pop(22))
train_cols.insert(20, train_cols.pop(23))
train = train[train_cols]

test_cols.insert(17, test_cols.pop(19))
test_cols.insert(18, test_cols.pop(20))
test_cols.insert(19, test_cols.pop(21))
test_cols.insert(20, test_cols.pop(22))
test = test[test_cols]

In [82]:
train['MonthlyCharges'].describe()

count    594194.000000
mean         65.866223
std          31.067444
min          18.250000
25%          29.900000
50%          74.100000
75%          90.800000
max         118.750000
Name: MonthlyCharges, dtype: float64

In [83]:
train['MonthlyCharges'].unique()

array([ 60.1 ,  69.5 , 100.4 , ...,  18.45, 112.05,  46.15], shape=(1921,))

In [84]:
train['MonthlyCharges'].value_counts()

MonthlyCharges
20.05    7436
19.95    5718
19.70    5705
20.00    5493
19.85    5114
         ...
32.45       1
31.30       1
89.24       1
21.70       1
46.15       1
Name: count, Length: 1921, dtype: int64

In [85]:
train['MonthlyCharges'], mc_bins = pd.qcut(train['MonthlyCharges'], q = 4, labels=[1, 2, 3, 4], retbins = True)
test['MonthlyCharges'] = pd.cut(test['MonthlyCharges'], bins = mc_bins, labels=[1, 2, 3, 4], include_lowest = True)

In [86]:
train['TotalCharges'].describe()

count    594194.000000
mean       2494.377057
std        2353.916710
min          18.800000
25%         639.650000
50%        1433.650000
75%        4263.800000
max        8684.800000
Name: TotalCharges, dtype: float64

In [87]:
train['TotalCharges'].unique()

array([1653.85, 3778.2 , 5841.35, ..., 1478.9 , 1284.75, 5460.7 ],
      shape=(31910,))

In [88]:
train['TotalCharges'].value_counts()

TotalCharges
6096.90    850
1110.05    846
6448.05    734
854.90     721
7133.25    619
          ...
5928.95      1
5813.20      1
2813.55      1
3238.80      1
157.25       1
Name: count, Length: 31910, dtype: int64

In [89]:
train['TotalCharges'], tc_bins = pd.qcut(train['TotalCharges'], q = 4, labels=[1, 2, 3, 4], retbins = True)
test['TotalCharges'] = pd.cut(test['TotalCharges'], bins = tc_bins, labels=[1, 2, 3, 4], include_lowest = True)

In [90]:
train['Churn'].describe()

count     594194
unique         2
top           No
freq      460377
Name: Churn, dtype: object

In [91]:
train['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [92]:
train['Churn'].value_counts()

Churn
No     460377
Yes    133817
Name: count, dtype: int64

In [93]:
train['Churn'] = train['Churn'].map({'Yes': 1, 'No': 0})

In [94]:
train

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService_DSL,InternetService_FiberOptic,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod_ElectronicCheck,PaymentMethod_MailedCheck,PaymentMethod_CreditCard,PaymentMethod_BankTransfer,MonthlyCharges,TotalCharges,Churn
0,0,0,1,1,3,1,0,1,0,1,...,0,1,1,0,1,0,0,2,3,0
1,0,0,1,1,5,1,0,1,0,1,...,0,2,0,0,0,1,0,2,3,0
2,0,0,1,0,5,1,1,0,1,0,...,1,0,1,1,0,0,0,4,4,0
3,1,0,0,0,1,1,0,0,1,0,...,0,0,1,1,0,0,0,2,1,1
4,1,0,0,0,1,1,0,0,1,0,...,0,0,1,1,0,0,0,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,0,0,0,0,5,1,1,0,1,0,...,1,2,0,0,0,0,1,4,4,0
594190,1,0,0,0,6,1,1,1,0,1,...,1,2,0,0,0,0,1,4,4,0
594191,1,0,1,0,6,1,1,0,0,0,...,0,2,0,0,0,1,0,1,3,0
594192,1,0,0,0,3,1,1,0,1,0,...,1,0,1,1,0,0,0,3,3,0
594193,1,1,1,0,1,1,0,1,0,0,...,0,0,1,1,0,0,0,2,1,1

In [95]:
test

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService_DSL,InternetService_FiberOptic,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod_ElectronicCheck,PaymentMethod_MailedCheck,PaymentMethod_CreditCard,PaymentMethod_BankTransfer,MonthlyCharges,TotalCharges
0,1,0,1,0,6,1,1,0,1,1,...,1,1,2,1,1,0,0,0,4,4
1,1,0,1,0,6,1,0,0,0,0,...,0,0,2,0,0,0,0,1,1,2
2,0,0,0,0,1,1,0,1,0,1,...,0,0,0,1,0,0,0,1,2,1
3,0,0,1,1,6,1,1,1,0,1,...,1,1,2,0,0,0,1,0,3,4
4,1,0,0,0,2,1,0,0,1,1,...,1,1,0,0,1,0,0,0,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254650,0,0,1,1,6,1,0,0,0,0,...,0,0,2,0,0,0,1,0,1,3
254651,0,1,1,0,2,1,1,0,1,0,...,1,1,0,1,1,0,0,0,4,3
254652,0,0,1,0,3,1,1,0,1,1,...,1,1,0,1,0,0,0,1,4,3
254653,1,0,0,0,3,1,0,0,0,0,...,0,0,2,1,0,0,1,0,1,1
254654,1,0,0,0,2,1,1,0,1,0,...,1,0,0,1,0,0,1,0,3,3

In [96]:
print("Train shape:", train.shape)
print("Test shape: ", test.shape)
 
print("Train columns:", train.columns.tolist())

Train shape: (594194, 24)
Test shape:  (254655, 23)
Train columns: ['Gender', 'SeniorCitizen', 'Partner', 'Dependents', 'Tenure', 'PhoneService', 'MultipleLines', 'InternetService_DSL', 'InternetService_FiberOptic', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod_ElectronicCheck', 'PaymentMethod_MailedCheck', 'PaymentMethod_CreditCard', 'PaymentMethod_BankTransfer', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [97]:
train.to_csv('train.csv', index = False)
test.to_csv('test.csv', index = False)