In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv("/kaggle/input/notebooks/shreyaashambhavii/exploratory-data-analysis-and-preprocessing/train.csv")
test = pd.read_csv("/kaggle/input/notebooks/shreyaashambhavii/exploratory-data-analysis-and-preprocessing/test.csv")

In [3]:
train

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,1,3,1,0,2,1,0,1,1,0,0,1,1,2,2,3,0
1,0,0,1,1,5,1,0,2,1,1,0,1,1,0,2,0,3,2,3,0
2,0,0,1,0,5,1,1,1,0,1,0,0,1,1,0,1,1,4,4,0
3,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,1,2,1,1
4,1,0,0,0,1,1,0,1,0,0,0,0,0,0,0,1,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,0,0,0,0,5,1,1,1,0,0,1,0,1,1,2,0,4,4,4,0
594190,1,0,0,0,6,1,1,2,1,1,1,1,1,1,2,0,4,4,4,0
594191,1,0,1,0,6,1,1,0,0,0,0,0,0,0,2,0,3,1,3,0
594192,1,0,0,0,3,1,1,1,0,0,0,0,0,1,0,1,1,3,3,0
594193,1,1,1,0,1,1,0,2,0,0,0,0,1,0,0,1,1,2,1,1

In [4]:
test

,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,1,0,1,0,6,1,1,1,1,1,1,1,1,1,2,1,1,4,4
1,1,0,1,0,6,1,0,0,0,0,0,0,0,0,2,0,4,1,2
2,0,0,0,0,1,1,0,2,1,1,0,0,0,0,0,1,4,2,1
3,0,0,1,1,6,1,1,2,1,0,1,1,1,1,2,0,3,3,4
4,1,0,0,0,2,1,0,1,1,0,0,0,1,1,0,0,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254650,0,0,1,1,6,1,0,0,0,0,0,0,0,0,2,0,3,1,2
254651,0,1,1,0,2,1,1,1,0,0,0,1,1,1,0,1,1,4,3
254652,0,0,1,0,3,1,1,1,1,0,1,1,1,1,0,1,4,4,3
254653,1,0,0,0,3,1,0,0,0,0,0,0,0,0,2,1,3,1,1
254654,1,0,0,0,2,1,1,1,0,0,1,0,1,0,0,1,3,3,3

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [6]:
X = train.drop('Churn', axis = 1)
y = train['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [7]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 1. Logistic Regression

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [10]:
log_reg = LogisticRegression(max_iter = 1000, random_state = 42)

cv_scores = cross_val_score(log_reg, X_train, y_train, cv = 5, scoring = 'roc_auc', n_jobs = -1)

print("--- Logistic Regression ---")
print(f"All 5 Fold Scores: {np.round(cv_scores, 4)}")
print(f"Mean CV ROC AUC:   {cv_scores.mean():.4f} (+/- {cv_scores.std():.4f})")

--- Logistic Regression ---
All 5 Fold Scores: [0.9017 0.8999 0.9018 0.9011 0.8995]
Mean CV ROC AUC:   0.9008 (+/- 0.0010)